Reusable workflow updates (#94)
* Create reusable workflow documentation

* Fix version workflow logic by addition update flag to control PR creation

Fix input descriptions
Update logic to use explicit cache save and file removal instead of git add ignore

* Update documentation

* Revise doc text

* Update description examples

* Reorder inputs and rename from verify to validate

* Update docs

* Update action versions to latest and update descriptions

* TEST: Update version validation logic to use programmatic tag

* Fix call

* TEST: use workflow defined caching instead

* Revert back to prod config and remove outdated code

* Test simplified update flag logic using github ternary and apply testing config

* Revert to prod config

Reorder input params for consistency

* TEST: nested reusable workflow for version

* Fix reusable workflow usage syntax

* Apply testing config

* Replace version validation in release scripts with reusable workflow call

Update how tags are used for reusable workflows to be locally defined instead of passed

* Remove required workflow_tag

* Enforce job dependency on validate versions

* Add check for tag existing before publishing pod

* Fix logic

* Try different git tag verification logic

* Update error message to use gh annotation format

* Apply production configs

Update android release to use updated remote tag check

diff --git a/.github/workflows/android-maven-release.yml b/.github/workflows/android-maven-release.yml
--- a/.github/workflows/android-maven-release.yml
+++ b/.github/workflows/android-maven-release.yml
@@ -24,29 +24,29 @@ on:
   workflow_call:
     inputs:
       tag:
-        description: >
+        description: |
           The tag (version) to be released (ex: 1.2.3). The workflow will automatically prepend the "v" prefix, resulting in a tag like "v1.2.3".
         type: string
         required: true
 
       create-github-release:
-        description: >
+        description: |
           Boolean flag that determines whether to create a GitHub release. If the specified `tag` does not exist, it will be created.
         type: boolean
         required: true
         default: true
 
       release-variant:
-        description: > 
+        description: | 
           The variant used to control the GitHub release title suffix and Maven publish command (ex: core -> v3.2.1-core & make core-publish-main). 
           If not specified, uses the default values for both.
         type: string
         required: false
         default: ''
 
-      version-verify-paths:
-        description: >
-          A comma-separated list of absolute or relative file paths to verify. 
+      version-validation-paths:
+        description: |
+          A comma-separated list of absolute and/or relative file paths to validate. 
           Each path can optionally specify a pattern type using the syntax:
           
           **Syntax:** `path[:file_type]`
@@ -58,31 +58,38 @@ on:
         type: string
         required: true
 
-      version-verify-dependencies:
-        description: >
-          A comma-separated list of dependencies with their versions. Each dependency can 
-          optionally specify the semicolon-separated list of file paths where it applies using the `@` symbol.
+      version-validation-dependencies:
+        description: |
+          A comma-separated list of dependencies with their versions. 
+          Each dependency can optionally specify a semicolon-separated list of the file paths where it applies using the `@` symbol.
           
           **Syntax:** `<name> <version>[@file_path1[;file_path2;...]]`
 
           - If the `@` syntax is used, the dependency will only apply to the specified files.
           - If the `@` symbol is omitted, the dependency applies to all relevant files.
-          - When specifying custom files, you must provide either an absolute or relative path to each file.
+          - When specifying custom file paths, you must provide either an absolute or relative path to each file.
+          - If a dependency is missing a version, it will be skipped.
 
           **Example:**
-          `"Core 7.8.9, EdgeIdentity 8.9.10@code/gradle.properties"`
+          `"Core 7.8.9, EdgeIdentity 8.9.10@code/gradle.properties;code/Constants.kt"`
         type: string
         required: false
         default: ''
 
-      workflow_tag:
-        description: 'The tag or ref of the reusable workflow being invoked (ex: gha-android-1.0.0).'
-        type: string
-        required: true
-
 jobs:
+  validate-versions:
+    name: Validate Versions
+    uses: adobe/aepsdk-commons/.github/workflows/versions.yml@gha-android-3.0.0
+    with:
+      version: ${{ github.event.inputs.tag }}
+      branch: ${{ github.ref_name }}
+      paths: ${{ inputs.version-validation-paths }}
+      dependencies: ${{ inputs.version-validation-dependencies }}
+      update: false
+
   publish:
     runs-on: ubuntu-latest
+    needs: validate-versions
     steps:
       - uses: actions/checkout@v4.1.7
 
@@ -98,43 +105,10 @@ jobs:
           path: ~/.gradle/caches
           key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
           restore-keys: ${{ runner.os }}-gradle
-      
-      - name: Restore cached scripts from aepsdk-commons
-        id: cache-scripts
-        uses: actions/cache@v4.1.1
-        with:
-          path: .github/aepsdk-commons/scripts
-          key: aepsdk-commons-${{ inputs.workflow_tag }} # Cache key format: <REPO_NAME>-<TAG>
-
-      - name: Download scripts from aepsdk-commons
-        if: steps.cache-scripts.outputs.cache-hit != 'true'
-        uses: actions/checkout@v4.1.7
-        with:
-          repository: adobe/aepsdk-commons
-          ref: ${{ inputs.workflow_tag }}
-          path: .github/aepsdk-commons
-          sparse-checkout: 'scripts' # Only checkout the scripts directory
-
-      - uses: actions/cache/save@v4.1.1
-        if: steps.cache-scripts.outputs.cache-hit != 'true'
-        with:
-          path: .github/aepsdk-commons/scripts
-          key: aepsdk-commons-${{ inputs.workflow_tag }} # Cache key format: <REPO_NAME>-<TAG>
-        
-      - name: Verify versions
-        run: |
-          set -eo pipefail
-          echo Release version: ${{ github.event.inputs.tag }}
-          python3 ./.github/aepsdk-commons/scripts/versions.py \
-            -v "${{ github.event.inputs.tag }}" \
-            -p "${{ inputs.version-verify-paths }}" \
-            -d "${{ inputs.version-verify-dependencies }}"
-
-      - name: Remove scripts from aepsdk-commons
-        run: rm -rf .github/aepsdk-commons
 
       - name: Create GitHub release
         if: ${{ inputs.create-github-release }}
+        continue-on-error: true
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
@@ -155,7 +129,16 @@ jobs:
         env:
           GPG_SECRET_KEYS: ${{ secrets.GPG_SECRET_KEYS }}
           GPG_OWNERTRUST: ${{ secrets.GPG_OWNERTRUST }}
+          TAG: ${{ inputs.tag }}
         run: |
+          # Check if the tag exists in the remote repository
+          if [ -z "$(git ls-remote --tags origin refs/tags/$TAG)" ]; then
+              echo "::error title=Missing tag for publishing Pods::Tag '$TAG' does not exist in the remote repository."
+              exit 1
+          else
+              echo "Tag '$TAG' exists in the remote repository."
+          fi
+
           echo $GPG_SECRET_KEYS | base64 --decode | gpg --import --no-tty --batch --yes
           echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust --no-tty --batch --yes
 
diff --git a/.github/workflows/ios-release.yml b/.github/workflows/ios-release.yml
--- a/.github/workflows/ios-release.yml
+++ b/.github/workflows/ios-release.yml
@@ -21,13 +21,13 @@ on:
   workflow_call:
     inputs:
       tag:
-        description: >
+        description: |
           The tag (version) to be released (ex: 1.2.3).
         type: string
         required: true
 
       create-github-release:
-        description: >
+        description: |
           Creates a single GitHub release and uploads artifacts for the specified extensions.  
           If the provided `tag` does not exist, it will be created.  
           This does **not** publish the pods to CocoaPods (use `pod-publish-extensions` for that).  
@@ -40,7 +40,7 @@ on:
         default: ''
 
       release-dependency-frameworks:
-        description: >
+        description: |
           **(Core-only parameter)**  
           A comma-separated list of extension frameworks to include as artifacts in the GitHub release.  
           The versions will be fetched from CocoaPods.  
@@ -53,7 +53,7 @@ on:
         default: ''
 
       pod-publish-extensions:
-        description: >
+        description: |
           Publishes the specified extensions to CocoaPods.  
           Pods will be published in the order they are listed.  
 
@@ -63,11 +63,53 @@ on:
         type: string
         required: true
         default: ''
+      
+      version-validation-paths:
+        description: |
+          A comma-separated list of absolute and/or relative file paths to validate. 
+          Each path can optionally specify a pattern type using the syntax:
+          
+          **Syntax:** `path[:file_type]`
+
+          **Example:**
+          `"Package.swift:swift_spm, AEPCore/Sources/configuration/ConfigurationConstants.swift, AEPCore/Tests/MobileCoreTests.swift:swift_test_version"`
+
+          This argument is required.
+        type: string
+        required: true
+
+      version-validation-dependencies:
+        description: |
+          A comma-separated list of dependencies with their versions. 
+          Each dependency can optionally specify a semicolon-separated list of the file paths where it applies using the `@` symbol.
+          
+          **Syntax:** `<name> <version>[@file_path1[;file_path2;...]]`
+
+          - If the `@` syntax is used, the dependency will only apply to the specified files.
+          - If the `@` symbol is omitted, the dependency applies to all relevant files.
+          - When specifying custom file paths, you must provide either an absolute or relative path to each file.
+          - If a dependency is missing a version, it will be skipped.
+
+          **Example:**
+          `"AEPCore 3.1.1, AEPServices 8.9.10@AEPCore.podspec;AEPIdentity.podspec"`
+        type: string
+        required: false
+        default: ''
 
 jobs:
+  validate-versions:
+    name: Validate Versions
+    uses: adobe/aepsdk-commons/.github/workflows/versions.yml@gha-ios-5.0.0
+    with:
+      version: ${{ github.event.inputs.tag }}
+      branch: ${{ github.ref_name }}
+      paths: ${{ inputs.version-validation-paths }}
+      dependencies: ${{ inputs.version-validation-dependencies }}
+      update: false
+
   release:
     runs-on: macos-latest
-
+    needs: validate-versions
     steps:
     - uses: actions/checkout@v4.1.7
       with:
@@ -83,12 +125,6 @@ jobs:
 
     - name: Install XcodeGen
       run: brew install xcodegen
-
-    - name: Check version in Podspec 
-      run: |
-        set -eo pipefail
-        echo Target version: ${{ inputs.tag }}
-        make check-version VERSION=${{ inputs.tag }}
 
     - name: Pod repo update
       if: ${{ inputs.create-github-release != '' }}
@@ -117,6 +153,7 @@ jobs:
 
     - name: Create GitHub release and upload assets
       if: ${{ inputs.create-github-release != '' }}
+      continue-on-error: true
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         CREATE_GITHUB_RELEASE: ${{ inputs.create-github-release }}
@@ -169,8 +206,17 @@ jobs:
       env:
         POD_PUBLISH_EXTENSIONS: ${{ inputs.pod-publish-extensions }}
         COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
+        TAG: ${{ inputs.tag }}
       run: |
         set -eo pipefail
+
+        # Check if the tag exists in the remote repository
+        if [ -z "$(git ls-remote --tags origin refs/tags/$TAG)" ]; then
+            echo "::error title=Missing tag for publishing Pods::Tag '$TAG' does not exist in the remote repository."
+            exit 1
+        else
+            echo "Tag '$TAG' exists in the remote repository."
+        fi
 
         # Split the input string into an array using comma as delimiter
         IFS=',' read -ra LIBS <<< "${POD_PUBLISH_EXTENSIONS}"
